# Generated by Django 4.1.5 on 2024-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseparty',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
