# Generated by Django 4.1.5 on 2023-02-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_location_places'),
        ('user', '0002_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_location', to='club.location'),
        ),
    ]
