# Generated by Django 4.1.5 on 2023-02-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_type_slug'),
        ('user', '0003_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='music',
            field=models.ManyToManyField(related_name='user_music', to='club.music'),
        ),
    ]
