# Generated by Django 4.1.5 on 2023-06-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('user', '0004_user_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='notifications.notification'),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
