# Generated by Django 4.1.5 on 2023-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='id',
            field=models.CharField(max_length=555, primary_key=True, serialize=False),
        ),
    ]
