# Generated by Django 4.1.5 on 2023-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='music',
            field=models.ManyToManyField(to='club.music'),
        ),
    ]
