# Generated by Django 4.1.5 on 2023-01-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_drink_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='name',
        ),
    ]
