# Generated by Django 4.1.5 on 2023-02-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_address_remove_place_location_delete_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='Address',
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_type', to='club.type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='upcoming_live_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_event', to='club.event'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('places', models.ManyToManyField(related_name='location_places', to='club.place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_address', to='club.address'),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_location', to='club.location'),
        ),
    ]
