# Generated by Django 4.1.5 on 2023-02-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_place_address_alter_place_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='places',
            field=models.ManyToManyField(blank=True, related_name='location_places', to='club.place'),
        ),
    ]
