# Generated by Django 4.1.5 on 2023-02-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_location_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
