# Generated by Django 4.1.5 on 2023-03-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0007_type_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='atendees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='events',
            field=models.ManyToManyField(blank=True, to='club.event'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='place_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='upcoming_live_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_event', to='club.event'),
        ),
    ]
