# Generated by Django 4.1.5 on 2023-03-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_remove_place_address_place_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event_pics'),
        ),
    ]
