# Generated by Django 4.1.5 on 2023-06-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=55)),
                ('text', models.TextField(max_length=200)),
                ('url', models.URLField()),
                ('recieved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
